### ISSUE TITLE
BUG: List of favorites is not updated after first visit to "Favorites" page

### ISSUE THREAD

**Issue by ThadT** [ThadT/bike-rental-stations-maui#1]
After initially viewing a set of favorite bike stations in the "Favorites" page, the list remains static no matter how many favorite stations are added/removed from the list.

To reproduce:
- Launch the app and select a city from the list
- When the bike stations draw, click a few stations in the map and then click the button in the callout to make them favorites

![image](https://github.com/ThadT/bike-rental-stations-maui/assets/5686282/6ecf1df4-6466-4f33-91bb-f6ae5f244f4d)

- Go to the favorites page; you will see the list of stations you made favorites

![image](https://github.com/ThadT/bike-rental-stations-maui/assets/5686282/3232f560-b93c-48a4-aa58-f56a0c2dbf29)

- Return to the map and add more favorites (or unfavorite some of your favorite stations)
- Go to the favorites page again and you will see the same list

**Comment by gdestigter** [comment]
I see the issue with this one.

The favorites list in XAML is bound to this dictionary in the VM: 
```
    [ObservableProperty]
    private Dictionary<long, Favorite> _favoriteBikeStations = new();
```

The dictionary is an observable property in the VM, but the dictionary itself is not observable (indeed, no `ObservableDictionary` exists in standard .NET). The first time the page is opened it picks up the initial values from the dictionary as this is the first time the VM is accessed and bound; but, once the page is setup, the dictionary gives no INPC / collection-changed notifications so new favorites are updated in the list.

This fix is probably to make `FavoriteBikeStations` an `ObservableCollection<Favorite>`. This does force a search of the collection in `CheckIsFavorite` which could be slow if there are tons of favorites - but doesn't seem like that would be the case.

**Comment by ThadT** [comment]
Thanks, @gdestigter!
I kept the dictionary for maintaining a unique list of favorites and then use an observable collection to bind the favorites. I might clean up this logic later, but it works for now 👍 
https://github.com/ThadT/bike-rental-stations-maui/blob/main/ViewModel/CityBikesViewModel.cs#L149-L166
